name: project-v4-sample

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      tools_k8s_version: 1.28.3
      kind_version: 0.20.0
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20'

      - name: Install Kind
        run: go install sigs.k8s.io/kind@v$kind_version
  

      - name: Install setup-envtest
        run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

      - name: Install e2e tools with setup-envtest
        run: setup-envtest use $tools_k8s_version

      - name: Create kind cluster
        run: kind create cluster --image kindest/node:v$tools_k8s_version

      - name: Prepare the environment
        run: |
          KUSTOMIZATION_FILE_PATH="testdata/project-v4/config/default/kustomization.yaml"
          sed -i '25s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '27s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '42s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '46,143s/^#//' $KUSTOMIZATION_FILE_PATH
      
      - name: Test
        run: |
          cd testdata/project-v4
          go get -u ./...
          go mod tidy
          make test-e2e
